# azure-pipelines.yml
# Configuration file for building, running, and testing the BTI rJourney model on RSG's
# local test server, operated by Azure Pipelines. rJourney is a Free Pascal application that can
# be compiled and run on 64bit Windows, Linux, or Mac architecture.
#
# Code for rJourney is hosted at https://github.com/RSGInc/rJourney

# Azure will build/run tests if on beijing branch
trigger:
  branches:
    include:
    - beijing

# win64
pool: RSGLocal-Builds

variables:
  resourcesDir: $(Agent.HomeDirectory)\rJourney_resources
  resourcesRepo: RSGInc/rJourney_resources.git
  config: bti_azure_config.txt
  program: BTI_LongDistance_1_1

  # https://sourceforge.net/projects/freepascal/
  fpc: C:\ProgramData\Lazarus\fpc\3.0.4\bin\x86_64-win64\fpc.exe

steps:
- script: $(fpc) -h
  displayName: Check FPC

# Checkout the beijing branch
- task: PowerShell@2
  displayName: Get latest test data
  inputs:
    targetType: inline
    script: |
      if ( !(Test-Path "$(resourcesDir)") ) {
        git clone https://$(GH_TOKEN)@github.com/$(resourcesRepo) $(resourcesDir)
      }
      cd $(resourcesDir)
      git checkout beijing
      git reset --hard origin/beijing
      git lfs pull
      git pull
      git clean -fd

# Flags:
#   -Co fails build if integer overflow is detected
#   -Mdelphi required for Delphi 7 compatibility
- script: |
    cd $(System.DefaultWorkingDirectory)
    git clean -fd
    $(fpc) -Co -Mdelphi .\$(program).pas
  displayName: Compile rJourney

- script: |
    cd $(Agent.HomeDirectory)
    git checkout beijing
    rmdir /S /Q bti_azure_outputs
    mkdir bti_azure_outputs
    $(System.DefaultWorkingDirectory)\$(program).exe $(System.DefaultWorkingDirectory)\$(config)
  displayName: Run rJourney

- script: type $(System.DefaultWorkingDirectory)\*.log
  displayName: Show logfile

# Expect exact output
- script: |
    cd $(Agent.HomeDirectory)
    git diff --no-index --compact-summary --exit-code $(resourcesDir)\bti_azure_target_outputs bti_azure_outputs
  displayName: Compare outputs
