# azure-pipelines.yml
# Configuration file for building, running, and testing the rJourney model on RSG's
# local test server, operated by Azure Pipelines. rJourney is a Free Pascal application that can
# be compiled and run on 64bit Windows, Linux, or Mac architecture.
#
# Code for rJourney is hosted at https://github.com/RSGInc/rJourney_public

# Azure will build/run tests if on master branch, or if branch includes 'azure' keyword
trigger:
  branches:
    include:
    - master
    - '*azure*'

# system requirements:
# win64, fpc (64-bit), git, git-lfs, HDF5-1.8.19
pool: WRJSOFPPW01

strategy:
  maxParallel: 2
  matrix:
    DAT:
      config: rJourney_azure_dat_config.txt
      outputs: azure_dat_outputs
    OMX:
      config: rJourney_azure_omx_config.txt
      outputs: azure_omx_outputs

variables:
  resourcesDir: $(Agent.HomeDirectory)\rJourney_resources
  resourcesRepo: RSGInc/rJourney_resources.git
  program: rJourney_1_4

steps:
- script: fpc -h
  displayName: Check FPC

# Use git lfs to pull entire data files, not just pointers
- script: |
    if not exist $(resourcesDir) git clone https://$(GH_TOKEN)@github.com/$(resourcesRepo) $(resourcesDir)
    cd $(resourcesDir)
    git pull
    git reset --hard origin/master
    git lfs pull
    git clean -fd
  displayName: Get latest test data

# Flags:
#   -Co fails build if integer overflow is detected
#   -Mdelphi required for Delphi 7 compatibility
- script: |
    cd $(System.DefaultWorkingDirectory)
    git clean -fd
    fpc -Mdelphi -Co -Ci -CR -Sh .\$(program).pas
  displayName: Compile rJourney

- script: |
    cd $(Agent.HomeDirectory)
    rmdir /S /Q $(outputs)
    mkdir $(outputs)
    $(System.DefaultWorkingDirectory)\$(program).exe $(System.DefaultWorkingDirectory)\$(config)
  displayName: Run rJourney

- script: type $(System.DefaultWorkingDirectory)\*.log
  displayName: Show logfile

- script: |
    cd $(Agent.HomeDirectory)
    git diff --no-index --compact-summary --exit-code $(resourcesDir)\azure_target_outputs $(outputs)
  displayName: Compare outputs
